application_dir = "maya"
default_dirs = [
	"scenes",
	"data",
	"renderData/shaders",
	"images"
]
label = "Autodesk Maya 2018"
ftrack_label = "Maya"
schema = "avalon-core:application-1.0"
executable = "maya2018"
description = ""
icon = "http://icons.iconarchive.com/icons/froyoshark/enkel/512/Maya-icon.png"

[copy]
"{PYPE_STUDIO_CONFIG}/res/workspace.mel" = "workspace.mel"
