executable = "premiere_pro_2019"
schema = "avalon-core:application-1.0"
application_dir = "premiere"
label = "Adobe Premiere Pro CC 2019"
icon = "premiere_icon"
preactions = ["aport"]

ftrack_label = "Premiere"
ftrack_icon = "https://upload.wikimedia.org/wikipedia/commons/4/40/Adobe_Premiere_Pro_CC_icon.svg"
