schema = "avalon-core:application-1.0"
application_dir = "python"
executable = "python"
label = "Python 2"

[environment]
CREATE_NEW_CONSOLE = "Yes"
MAYA_DISABLE_CLIC_IPM = "Yes"  # Disable the AdSSO process
MAYA_DISABLE_CIP = "Yes"  # Shorten time to boot
MAYA_DISABLE_CER = "Yes"
PYMEL_SKIP_MEL_INIT = "Yes"
LC_ALL= "C"  # Mute color management warnings
PYTHONPATH = [
	"{AVALON_CORE}/setup/maya",
	"{PYTHONPATH}"
]
