# nuke
# [{software}.{object}]
#   attribute
[nuke.root]
  colorManagement = "OCIO"
  OCIO_config = "aces_1.0.3"
  workingSpaceLUT = "ACES - ACEScg"
  defaultViewerLUT = "OCIO LUTs"
  monitorLut = "ACES/sRGB D60 sim."
  int8Lut = "Utility - sRGB - Texture"
  int16Lut = "Utility - sRGB - Texture"
  logLut = "Input - ARRI - V3 LogC (EI800) - Wide Gamut"
  floatLut = "ACES - ACES2065-1"

[nuke.viewer]
  viewerProcess = "sRGB D60 sim. (ACES)"

[nuke.write.render]
  colorspace = "ACES - ACEScg"

[nuke.write.prerender]
  colorspace = "ACES - ACEScg"

[nuke.write.still]
  colorspace = "Utility - Curve - sRGB"
# Maya

# Hudiny

# Fusion
