EDITORIAL_PATH = '{AVALON_CORE}/setup/editorial/pythonpath'
PUBLISH_PATH = [
    '{PYPE_STUDIO_CONFIG}/{AVALON_CONFIG}/plugins/premiere/publish'
    ]
# settings of pico.server.run_app()
PICO_IP = "127.0.0.1"
PICO_PORT = 4242
PICO_DEBUG = false
PICO_RELOADER = false
PICO_THREADED = true
