FTRACK_SERVER="https://pype.ftrackapp.com"

FTRACK_ACTIONS_PATH = ["{PYPE_STUDIO_CONFIG}/pype/ftrack/actions"]
FTRACK_EVENTS_PATH = ["{PYPE_STUDIO_CONFIG}/pype/ftrack/events"]

FTRACK_ACTION_SERVER = "{PYPE_SETUP_ROOT}/repos/ftrack-event-server"

PYTHONPATH = ["{PYPE_APP_ROOT}/vendor",
              "{PYPE_STUDIO_CONFIG}/pype/vendor",
              "{PYPE_SETUP_ROOT}/repos/ftrack-event-server",
              "{PYPE_STUDIO_CONFIG}/pype/vendor/ftrack"]

PYBLISHPLUGINPATH = ["{PYPE_STUDIO_CONFIG}/pype/plugins/ftrack"]
