PYTHONPATH = [
    "{AVALON_CORE}/setup/maya",
    "{MAYA_LOOK_ASSIGNER}"
    ]

MAYA_DISABLE_CLIC_IPM = "Yes"  # Disable the AdSSO process
MAYA_DISABLE_CIP = "Yes"  # Shorten time to boot
MAYA_DISABLE_CER = "Yes"
PYMEL_SKIP_MEL_INIT = "Yes"
LC_ALL= "C"  # Mute color management warnings
