PYBLISH_GUI = ["lite"]

NUKE_PATH = [
    "{AVALON_CORE}/setup/nuke/nuke_path",
    "{PYPE_STUDIO_CONFIG}/setup/nuke/nuke_path",
    "{PYPE_STUDIO_PLUGINS}/nuke"
]

[PATH]
windows = 'C:/Program Files (x86)/QuickTime/QTSystem/'

[PYTHONPATH]
windows = "{PYTHON_ENV}/python2/Lib/site-packages"
