PYBLISH_GUI = ["pyblish_qml"]
PYBLISH_QML_MODAL = "1"
PYBLISH_QML_PYQT5 = "{PYTHON_ENV}/qt5/python-qt5"
PYBLISH_QML_PYTHON_EXECUTABLE = "{PYTHON_ENV}/python2/python.exe"

PYTHONPATH = [
    "{PYTHON_ENV}/qt5/python-qt5",
    "{PYTHON_ENV}/python2/Lib/site-packages"
]

NUKE_PATH = [
    "{AVALON_CORE}/setup/nuke/nuke_path",
    "{PYPE_STUDIO_CONFIG}/setup/nuke/nuke_path",
    "{PYPE_STUDIO_PLUGINS}/nuke"
]

[PATH]
windows = 'C:/Program Files (x86)/QuickTime/QTSystem/'
