PREMIERA_PATH = '{AVALON_CORE}/setup/premiere/pythonpath'
# PUBLISH_PATH = [
#     '{PYPE_STUDIO_CONFIG}/{AVALON_CONFIG}/plugins/premiere/publish'
#     ]

# this must be used in any host working with `aport`
PRESETS_PATH = ["{PYPE_STUDIO_TEMPLATES}/presets/premiere"]

[EXTENSIONS_PATH]
windows = "{USERPROFILE}/AppData/Roaming/Adobe/CEP/extensions"
darvin = "{USER}/Library/Application Support/Adobe/CEP/extensions"
