# studio storage locations
## pipeline (keys are mandatory)
PYPE_STUDIO_SOFTWARE = "{locations.kredenc.core.path}/software"
PYPE_STUDIO_TOOLS = "{locations.kredenc.core.path}/tools"
# PYPE_STUDIO_PIPELINE = "{locations.kredenc.pipeline.path}/pype-setup"

## project related (keys are mandatory)
PYPE_STUDIO_PROJECTS_RESOURCES = "{locations.kredenc.projects.work.path}"
PYPE_STUDIO_PROJECTS_WORK = "{locations.kredenc.projects.work.path}"
PYPE_STUDIO_PROJECTS_RENDER = "{locations.kredenc.projects.work.path}"
PYPE_STUDIO_PROJECTS_PUBLISH = "{locations.kredenc.projects.work.path}"

# local storage locations (keys are mandatory)
PYPE_LOCAL_PROJECTS = "{locations.local.projects.path}"
PYPE_LOCAL_CACHE = "{locations.local.cache.path}/pype-cache"
PYPE_LOCAL_SOFTWARE = "{locations.local.software.path}"
