# [studio.kredenc.projects.raw]
#   name = "kre-p02"
#   ip = "10.0.0.20"
#   api_key = "" # could be perhaps used for access
#   path = {windows = "W:/projects", darvin = "/Volume/projects", linux = "/mnt/projects"}
#
# [studio.kredenc.projects.plates]
#   name = "kre-p03"
#   ip = "10.0.0.30"
#   api_key = "" # could be perhaps used for access
#   path = {windows = "L:/projects", darvin = "/Volume/projects", linux = "/mnt/projects"}

[kredenc.projects.work]
  name = "kre-p01"
  ip = "10.0.0.2"
  api_key = "" # could be perhaps used for access
  path = {windows = "P:/projects/_AVALON", darvin = "/Volume/share/projects/_AVALON", linux = "/mnt/share/projects/_AVALON"}

# [kredenc.projects.render]
#   name = "kre-p01"
#   ip = "10.0.0.2"
#   api_key = "" # could be perhaps used for access
#   path = {windows = "R:/projects", darvin = "/Volume/projects", linux = "/mnt/projects"}
#
# [kredenc.projects.cache]
#   name = "kre-p05"
#   ip = "10.0.0.2"
#   api_key = "" # could be perhaps used for access
#   path = {windows = "Z:/projects", darvin = "/Volume/projects", linux = "/mnt/projects"}

[kredenc.library]
  name = "kre-d01"
  ip = "10.0.0.2"
  path = {windows = "L:/library", darvin = "/Volume/share/library", linux = "/mnt/share/library"}

[kredenc.core]
  name = "kre-c01"
  ip = "10.0.0.3"
  path = {windows = "K:/core", darvin = "/Volume/share/core", linux = "/mnt/share/core"}

[local.projects]
  name = "cache"
  path = {windows = "D:/projects", darvin = "/Volume/data/projects", linux = "/mnt/data/projects"}

[local.cache]
  name = "cache"
  path = {windows = "D:/cache", darvin = "/Volume/data/cache", linux = "/mnt/data/cache"}

[local.software]
  name = "software"
  path = {windows = "C:/Program Files", darvin = "/Applications", linux = "/user/local"}
