application_dir = "blender"
executable = "blender_280"
schema = "avalon-core:application-1.0"
label = "Blender 2.80"
ftrack_label = "Blender 2.80"
icon ="blender"
ftrack_icon = '{}/app_icons/blender.png'
