application_dir = "maya"
default_dirs = [
	"renders"
]
label = "Autodesk Maya 2019"
ftrack_label = "Maya"
schema = "avalon-core:application-1.0"
executable = "maya2019"
description = ""
icon ="maya_icon"
ftrack_icon = "http://icons.iconarchive.com/icons/froyoshark/enkel/512/Maya-icon.png"

[copy]
"{PYPE_STUDIO_CONFIG}/res/workspace.mel" = "workspace.mel"
