executable = "nukestudio10.0"
schema = "avalon-core:application-1.0"
application_dir = "nukestudio"
label = "NukeStudio 10.0"
ftrack_label = "NukeStudio"
icon ="nuke_icon"
ftrack_icon = "https://mbtskoudsalg.com/images/nuke-icon-png-2.png"
