# nuke
# List of nodes which need to be controlled or created
[nuke.nodes]
  connected = true  # connected by hierarchical order

  [nuke.nodes.modifymetadata]
    # hiearchy
    id = "connect_metadata"
    previous = "ENDING" # this will connect to end of the comp
    # attributes
    metadata.set.pype_studio_name = "{PYPE_STUDIO_NAME}"
    metadata.set.avalon_project_name = "{AVALON_PROJECT}"
    metadata.set.avalon_project_code = "{PYPE_STUDIO_CODE}"
    metadata.set.avalon_asset_name = "{AVALON_ASSET}"

  [nuke.nodes.crop]
    # hiearchy
    id = "connect_crop"
    previous = "connect_metadata"
    # attributes
    box = [
    # taken from whatever preset is selected
    # in metadata/<preset.toml>:bbox
    # it is hierarchical
    # it will be converted to int()
    "{metadata.crop.x}",
    "{metadata.crop.y}",
    "{metadata.crop.right}",
    "{metadata.crop.top}"
    ]

  [nuke.nodes.write.render]
    # hiearchy
    id = "output_write"
    previous = "connect_crop"
    # attributes
    file_type = "exr"
    datatype = "16 bit half"
    compression = "Zip (1 scanline)"
    create_directories = true
    autocrop = true
    tile_color = "0xff0000ff"
    channels = "rgb"

[nuke.nodes.write.prerender]
  # hiearchy
  id = "output_write"
  previous = "connect_crop"
  # attributes
  file_type = "exr"
  datatype = "16 bit half"
  compression = "Zip (1 scanline)"
  create_directories = true
  autocrop = true
  tile_color = "0xc9892aff"
  channels = "rgba"

  [nuke.nodes.write.still]
    # hiearchy
    previous = "connect_crop"
    # attributes
    channels = "rgba"
    file_type = "tiff"
    datatype = "16 bit"
    compression = "LZW"
    create_directories = true
    tile_color = "0x4145afff"
