# nuke
# List of nodes which need to be controlled or created
[nuke.nodes]
  connected = true  # connected by hierarchical order

  [nuke.nodes.ModifyMetaData]
    # hiearchy
    id = "connect_metadata"
    previous = "ENDING" # this will connect to end of the comp
    # attributes
    metadata.set.pype_studio_name = "{PYPE_STUDIO_NAME}"
    metadata.set.avalon_project_name = "{AVALON_PROJECT}"
    metadata.set.avalon_project_code = "{PYPE_STUDIO_CODE}"
    metadata.set.avalon_asset_name = "{AVALON_ASSET}"

  [nuke.nodes.Crop]
    # hiearchy
    id = "connect_crop"
    previous = "connect_metadata"
    # attributes
    box = [
    # taken from whatever preset is selected
    # in metadata/<preset.toml>:bbox
    # it is hierarchical
    # it will be converted to int()
    "{metadata.crop.x}",
    "{metadata.crop.y}",
    "{metadata.crop.right}",
    "{metadata.crop.top}"
    ]

  [nuke.nodes.Write]
    family = "render"
    # hiearchy
    id = "output_write"
    previous = "connect_crop"
    # attributes
    file_type = "exr"
    datatype = "16 bit half"
    compression = "Zip (1 scanline)"
