# core repos
[AVALON_CORE]
    name = "avalon-core"
    url = "git@github.com:pypeclub/avalon-core.git"
    branch = "develop"
    submodule_root = "repos"


[AVALON_LAUNCHER]
    name = "avalon-launcher"
    url = "git@github.com:pypeclub/avalon-launcher.git"
    branch = "develop"
    submodule_root = "repos"


[PYBLISH_BASE]
    name = "pyblish-base"
    url = "git@github.com:pyblish/pyblish-base.git"
    branch = "develop"
    submodule_root = "repos"


[PYBLISH_QML]
    name = "pyblish-qml"
    url = "git@github.com:pypeclub/pyblish-qml.git"
    branch = "develop"
    submodule_root = "repos"


[PYBLISH_LITE]
    name = "pyblish-lite"
    url = "git@github.com:pyblish/pyblish-lite.git"
    branch = "master"
    submodule_root = "repos"


# studio repos
[PYPE_STUDIO_CONFIG]
    name = "pype-config"
    url = "git@bitbucket.org:pypeclub/pype-config.git"
    branch = "develop"
    submodule_root = "repos"


[PYPE_STUDIO_TEMPLATES]
    name = "pype-templates"
    url = "git@bitbucket.org:pypeclub/pype-templates.git"
    branch = "develop"
    submodule_root = "repos"


[PYPE_STUDIO_PROJECTS]
    name = "pype-projects"
    url = "git@bitbucket.org:pypeclub/pype-projects.git"
    branch = "develop"
    submodule_root = "repos"


[FTRACK_EVENT_SERVER]
    name = "ftrack-event-server"
    url = "git@github.com:pypeclub/ftrack-event-server.git"
    branch = "master"
    submodule_root = "repos"

[MAYA_LOOK_ASSIGNER]
    name = "maya-look-assigner"
    url = "git@github.com:pypeclub/maya-look-assigner.git"
    branch = "master"
    submodule_root = "repos"
